Project completed
bouaik/TESTING_PRACTICE pull request #1
Opened 2020-09-20 12:34 UTC by bouaik

### Test javascript code with jest

2020-09-20 13:03 UTC, suretrust requested changes
Hi @bouaik, 👋 

### Great job thus far! 🙌 Please see my comments. 👇 

- [x] I tagged some as `optional`, it would be nice to implement them as they make your codebase follow best practices, but they are not a requirement.

**KIndly submit another CRR once these issues have been solved.** _Happy coding!_ 🎉

2020-09-20 13:03 UTC, suretrust commented on src/analyse.js
> +};
- [x] **`Optional`** You could move `average`, `min`, and `max` into the `analyse` function. It's always better to use pure functions where possible.

```suggestion
const analyse = (arr) => {
  const average = (arr) => arr.reduce((acc, num) => acc + num, 0) / arr.length;
  const min = (arr) => Math.min(...arr);
  const max = (arr) => Math.max(...arr);
 
  const analysed = {
    average: average(arr),
    min: min(arr),
    max: max(arr),
    length: arr.length,
  };
  return analysed;
};
```

2020-09-20 13:03 UTC, suretrust commented on test/capitalized.test.js
> +  expect(capitalized('hello')).toBe('Hello');
- [x] **`Optional`** Let's add a test for an empty string. When writing tests, it's always good to think about all edge cases.

2020-09-20 13:03 UTC, suretrust commented on test/ceaser_cipher.test.js
> +  expect(cipher('abc', 1)).toBe('bcd');
- [ ] Your test should have a case that wraps z to a. That way, you won't be missing out on anything.

2020-09-21 06:55 UTC, shloch approved these changes
Corrections made and project still working as well as tests

Keep up with the good work

HAPPY CODING

2020-09-21 07:03 UTC, merged